/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "udeflfcdqgjkgkmrazxk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZWZsZmNkcWdqa2drbXJhenhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzNzQ3OTMsImV4cCI6MjA4ODk1MDc5M30.lKR1YLr-_OxqNSPY7GdTwN-a-DF3vNv01QQMM8VnmUw"